language: python

python:
  - 3.5
  
services: postgresql

env:
  - DJANGO=1.8.15

before_install:
  - export DJANGO_SETTINGS_MODULE=project.settings
  - export PYTHONPATH=$HOME/builds/raahoolkumeriya/codelocked
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres

script:
  - python manage.py makemigrations --quiet
