# Generated by Django 2.1.4 on 2019-01-25 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_streamtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageView',
        ),
    ]
