# Generated by Django 2.1 on 2018-11-24 17:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0003_auto_20181124_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamtype',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
