# Generated by Django 2.1 on 2018-11-24 17:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0004_auto_20181124_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamtype',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
