# Generated by Django 2.1 on 2018-11-25 05:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0006_auto_20181125_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamtype',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
