# Generated by Django 2.1 on 2018-11-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0007_auto_20181125_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamtype',
            name='github',
            field=models.URLField(blank=True, default=''),
        ),
    ]
