# Generated by Django 2.1 on 2018-11-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0008_streamtype_github'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamtype',
            name='github',
            field=models.URLField(blank=True),
        ),
    ]
