# Generated by Django 2.1 on 2018-11-27 17:51

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('mywebsite', '0009_auto_20181125_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamtype',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
