# Generated by Django 2.1 on 2018-11-27 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0010_streamtype_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamtype',
            name='tags',
        ),
    ]
