# Generated by Django 2.1 on 2018-11-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0011_remove_streamtype_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamtype',
            name='tags',
            field=models.CharField(default='', max_length=30),
        ),
    ]
