# Generated by Django 2.1 on 2018-11-28 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0013_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='username',
        ),
    ]
