# Generated by Django 2.1 on 2018-11-28 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0014_auto_20181128_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='username',
            new_name='user',
        ),
    ]
